[workspace]
authors = ["Soham Karandikar <sohamk10@gmail.com>"]
channels = ["conda-forge"]
name = "rocky-slides"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]
generate = "python generate_slides.py"

[dependencies]
typst = ">=0.14.2,<0.15"
python = ">=3.14.4,<3.15"

[pypi-dependencies]
typst = ">=0.14.8, <0.15"
